AppBundle\Entity\Catalog\Phone:
  properties:
    voltage:
      - Type:
          type: integer
          groups: [create, update]
      - NotBlank:
          groups: [create, update]
    material:
      - Type:
          type: string
          groups: [create, update]
      - NotBlank:
          groups: [create, update]